version: '2'
services:
 svn:
  image: paul-hammant/alpine-svn-dav
  container_name: alpine_svn-dav
  hostname: alpine-svn-dav
  environment:
  - DAV_SVN_USER=davsvn
  - DAV_SVN_PASS=davsvn
  - SVN_REPO=repo
  ports:
  - "80"
#  volumes:
#  - /path/volumes/svn:/var/svn
  restart: always
